// Edit this file to change the wheel options, page colors and content.
export const sections = [
  {
    id: 'home',
    label: 'Home',
    bg: '#ffffff',
    fg: '#0a0a0a',
    title: 'Hi, I’m Angelos Karasavvidis.',
    body: 'I design and build clean, useful and complete things for the web.',
  },
  {
    id: 'about',
    label: 'About',
    bg: '#ffd23f',
    fg: '#0a0a0a',
    title: 'About me',
    body: 'Currently on my senior year (MSc/BEng in Electrical Engineering @NTUA), I have gained knowledge, mainly on software and AI enginering, automatic control and robotics. At the same time, through the organizations where I have volunteered, I have managed to acquire various soft skills, such as teamwork and communication. I am always willing to explore and learn something new.',
  },
  {
    id: 'projects',
    label: 'Past Projects',
    bg: '#2447ff',
    fg: '#ffffff',
    title: 'Past Projects',
    body: 'Project One — short description.\nProject Two — short description.\nProject Three — short description.',
  },
  {
    id: 'experience',
    label: 'Experience',
    bg: '#12a150',
    fg: '#ffffff',
    title: 'Experience',
    body: 'Company A — Role, 2023–now.\nCompany B — Role, 2021–2023.',
    // Opens a second wheel in front of the main one.
    children: [
      {
        id: 'work',
        label: 'Work',
        bg: '#12a150',
        fg: '#ffffff',
        title: 'Work',
        body: 'Company A — Role, 2023–now.\nCompany B — Role, 2021–2023.',
      },
      {
        id: 'volunteer',
        label: 'Volunteer',
        bg: '#e5575b',
        fg: '#ffffff',
        title: 'Volunteer',
        body: 'Organisation A — what you did.\nOrganisation B — what you did.',
      },
    ],
  },
  {
    id: 'skills',
    label: 'Skills',
    bg: '#7a3cff',
    fg: '#ffffff',
    title: 'Skills',
    body: 'React · TypeScript · Node · Design · Motion',
  },
  {
    id: 'contact',
    label: 'Contact',
    bg: '#0a0a0a',
    fg: '#ffffff',
    title: 'Let’s talk',
    body: '',
    // photo: '/angelos.jpg',
    links: [
      { label: 'Email', href: 'mailto:angelkarasavvidis@gmail.com' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/angelos-karasavvidis-3a3802231/' },
    ],
  },
]
